# --- CLASSE DE CONEXÃO: Configuração do MySQL ---
spring.datasource.url=jdbc:mysql://localhost:3306/bicicletario_db?createDatabaseIfNotExist=true
spring.datasource.username=appuser
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ADICIONE ESTA LINHA PARA FORÇAR O DIALETO
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect